//
//  Localization.swift
//  Локализация на 4 языках: RU, SK, EN, UA.
//

import Foundation

enum L10n {

    // MARK: - RU
    private static let ru: [String: String] = [
        "nav_chat":    "Чат с AI",
        "nav_alarms":  "Алармы",
        "nav_codes":   "G/M Коды",
        "nav_program": "Анализ программы",
        "nav_photo":   "Фото анализ",
        "nav_history": "История",
        "nav_machine": "Профиль станка",
        "settings":    "Настройки",
        "language":    "Язык",
        "alarm_label": "НОМЕР АЛАРМА",
        "alarm_ph":    "Например: 607, SV0401, EX1082",
        "alarm_quick": "ЧАСТЫЕ АЛАРМЫ",
        "code_label":  "G ИЛИ M КОД",
        "code_ph":     "Например: M30, G01, G54",
        "code_quick":  "ПОПУЛЯРНЫЕ КОДЫ",
        "prog_label":  "G-КОД ПРОГРАММЫ",
        "prog_ph":     "Вставьте G-код...",
        "photo_label": "ФОТО АНАЛИЗ",
        "photo_hint":  "Прикрепите фото экрана станка или детали\nAI определит алармы и даст рекомендации",
        "photo_add":   "📎  Прикрепить фото",
        "photo_go":    "Анализировать",
        "photo_q_ph":  "Вопрос по фото (необязательно)...",
        "photo_none":  "Фото не выбрано",
        "photo_err":   "Выберите фото",
        "photo_camera":"Камера",
        "photo_gallery":"Галерея",
        "chat_ph":     "Напишите вопрос по ЧПУ...",
        "chat_attach": "📎",
        "chat_send":   "Отправить",
        "chat_new":    "Новый чат",
        "chat_welcome":"Привет! Я AI-ассистент по Fanuc CNC.\n\nМогу помочь с:\n• Расшифровкой алармов\n• Объяснением G/M кодов\n• Анализом программ\n• Диагностикой по фото\n\nПишите вопрос или прикрепите фото 👇",
        "btn_analyze": "Расшифровать",
        "btn_explain": "Объяснить",
        "btn_prog":    "Проанализировать",
        "result_title":"РЕЗУЛЬТАТ",
        "result_empty":"Результат появится здесь...",
        "hist_title":  "История",
        "hist_clear":  "Очистить",
        "hist_empty":  "История пуста",
        "status_ready":"Готов к работе",
        "status_busy": "Анализирую...",
        "set_title":   "Настройки",
        "api_lbl":     "ANTHROPIC API KEY",
        "api_hint":    "console.anthropic.com  —  регистрация даёт $5 бесплатно",
        "api_save_cb": "Запомнить ключ",
        "save":        "Сохранить",
        "cancel":      "Отмена",
        "err_key":     "Введите API ключ в Настройках",
        "err_empty":   "Введите значение",
        "err_prog":    "Вставьте G-код",
        "sys":         "Ты эксперт по ЧПУ станкам Fanuc. ВАЖНО: всегда отвечай ТОЛЬКО на русском языке, даже если предыдущие сообщения были на другом языке. Давай конкретные решения.",
        "q_alarm":     "Расшифруй аларм Fanuc: %@\n1. Что означает\n2. Причины\n3. Как исправить\n4. Как предотвратить",
        "q_code":      "Объясни G/M код Fanuc: %@\n1. Что делает\n2. Формат\n3. Пример\n4. Нюансы",
        "q_prog":      "Проанализируй программу Fanuc:\n%@\n1. Что делает\n2. Разбор команд\n3. Ошибки\n4. Рекомендации",
        "q_photo":     "Проанализируй фото со станка Fanuc. Что видишь? Есть алармы/ошибки? Рекомендации.\nВопрос: %@",
        "q_photo0":    "Проанализируй фото со станка Fanuc. Что видишь? Есть алармы/ошибки? Дай рекомендации.",
        "badge_alarm": "Аларм",
        "badge_code":  "Код",
        "badge_prog":  "Программа",
        "badge_photo": "Фото",
        "badge_chat":  "Чат",
        "title_chat":    "Чат с AI",
        "title_alarms":  "Расшифровка алармов",
        "title_codes":   "Объяснение кодов",
        "title_program": "Анализ программы",
        "title_photo":   "Фото анализ",
        "title_history": "История",
        "title_machine": "Профиль станка",
        "machine_saved":         "Сохранено",
        "machine_save_btn":      "Сохранить профиль",
        "mach_model":            "МОДЕЛЬ СТАНКА",
        "mach_model_ph":         "Например: Fanuc 0i-MF",
        "mach_ctrl":             "СТОЙКА (КОНТРОЛЛЕР)",
        "mach_ctrl_ph":          "Например: Fanuc 0i-MD",
        "mach_axes":             "ОСИ",
        "mach_axes_ph":          "Например: X, Y, Z, A",
        "mach_maxspeed":         "МАК. СКОРОСТЬ ОБ/МИН",
        "mach_maxspeed_ph":      "Например: 8000",
        "mach_maxfeed":          "МАК. ПОДАЧА ММ/МИН",
        "mach_maxfeed_ph":       "Например: 10000",
        "mach_tools":            "ИНСТРУМЕНТЫ / МАГАЗИН",
        "mach_tools_ph":         "Например: 24 инструмента, BT40",
        "mach_materials":        "ОБРАБАТЫВАЕМЫЕ МАТЕРИАЛЫ",
        "mach_materials_ph":     "Например: сталь, алюминий, нержавейка",
        "mach_tolerances":       "ДОПУСКИ",
        "mach_tolerances_ph":    "Например: +/-0.01 мм",
        "mach_postproc":         "ПОСТПРОЦЕССОР / ОСОБЕННОСТИ",
        "mach_postproc_ph":      "Например: Heidenhain, субпрограммы, макросы",
        "mach_notes":            "ЗАМЕТКИ О СТАНКЕ",
        "mach_notes_ph":         "Любая дополнительная информация...",
        "prog_chat_ph":          "Задайте уточняющий вопрос по программе...",
        "btn_improve":           "Улучшить код",
        "btn_improve_explain":   "Что улучшить",
        "improved_code_lbl":     "УЛУЧШЕННЫЙ КОД",
        "improve_explain_lbl":   "ЧТО УЛУЧШЕНО",
        "q_prog_machine":        "Проанализируй программу Fanuc с учётом параметров станка:\n\nСТАНОК:\n%@\n\nПРОГРАММА:\n%@\n\n1. Что делает программа\n2. Разбор команд\n3. Ошибки и несоответствия\n4. Рекомендации",
        "q_improve":             "Улучши эту программу Fanuc:\n\nСТАНОК:\n%@\n\nПРОГРАММА:\n%@\n\nВерни:\n1. ОБЪЯСНЕНИЕ: что было улучшено\n2. УЛУЧШЕННЫЙ КОД: готовый G-код",
        "q_improve_explain":     "Объясни что можно улучшить (без кода):\n\nСТАНОК:\n%@\n\nПРОГРАММА:\n%@\n\n1. Что не оптимально\n2. Что улучшить\n3. Проблемы\n4. Рекомендации",
        "model_label":           "Модель",
        "send":                  "Отправить",
        "loading":               "Загрузка...",
        "copy":                  "Копировать",
        "delete":                "Удалить",
        "rename":                "Переименовать",
        "ok":                    "OK",
        "no_results":            "Нет результатов",
        "more":                  "Ещё",
    ]

    // MARK: - SK
    private static let sk: [String: String] = [
        "nav_chat":    "Chat s AI",
        "nav_alarms":  "Alarmy",
        "nav_codes":   "G/M Kódy",
        "nav_program": "Analýza programu",
        "nav_photo":   "Foto analýza",
        "nav_history": "História",
        "nav_machine": "Profil stroja",
        "settings":    "Nastavenia",
        "language":    "Jazyk",
        "alarm_label": "ČÍSLO ALARMU",
        "alarm_ph":    "Napr.: 607, SV0401, EX1082",
        "alarm_quick": "ČASTÉ ALARMY",
        "code_label":  "G ALEBO M KÓD",
        "code_ph":     "Napr.: M30, G01, G54",
        "code_quick":  "POPULÁRNE KÓDY",
        "prog_label":  "G-KÓD PROGRAMU",
        "prog_ph":     "Vložte G-kód...",
        "photo_label": "FOTO ANALÝZA",
        "photo_hint":  "Priložte foto obrazovky stroja alebo dielu\nAI určí alarmy a dá odporúčania",
        "photo_add":   "📎  Priložiť foto",
        "photo_go":    "Analyzovať",
        "photo_q_ph":  "Otázka k foto (nepovinné)...",
        "photo_none":  "Foto nie je vybrané",
        "photo_err":   "Vyberte foto",
        "photo_camera":"Kamera",
        "photo_gallery":"Galéria",
        "chat_ph":     "Napíšte otázku o CNC...",
        "chat_attach": "📎",
        "chat_send":   "Odoslať",
        "chat_new":    "Nový chat",
        "chat_welcome":"Ahoj! Som AI asistent pre Fanuc CNC.\n\nMôžem pomôcť s:\n• Dešifrovaním alarmov\n• Vysvetlením G/M kódov\n• Analýzou programov\n• Diagnostikou podľa foto\n\nNapíšte otázku alebo priložte foto 👇",
        "btn_analyze": "Dešifrovať",
        "btn_explain": "Vysvetliť",
        "btn_prog":    "Analyzovať",
        "result_title":"VÝSLEDOK",
        "result_empty":"Výsledok sa zobrazí tu...",
        "hist_title":  "História",
        "hist_clear":  "Vymazať",
        "hist_empty":  "História je prázdna",
        "status_ready":"Pripravený",
        "status_busy": "Analyzujem...",
        "set_title":   "Nastavenia",
        "api_lbl":     "ANTHROPIC API KEY",
        "api_hint":    "console.anthropic.com  —  registrácia dáva $5 zadarmo",
        "api_save_cb": "Zapamätať kľúč",
        "save":        "Uložiť",
        "cancel":      "Zrušiť",
        "err_key":     "Zadajte API kľúč v Nastaveniach",
        "err_empty":   "Zadajte hodnotu",
        "err_prog":    "Vložte G-kód",
        "sys":         "Si expert na CNC stroje Fanuc. DÔLEŽITÉ: vždy odpovedaj IBA po slovensky, aj keď boli predchádzajúce správy v inom jazyku. Dávaj konkrétne riešenia.",
        "q_alarm":     "Dešifruj alarm Fanuc: %@\n1. Čo znamená\n2. Príčiny\n3. Ako opraviť\n4. Ako predísť",
        "q_code":      "Vysvetli G/M kód Fanuc: %@\n1. Čo robí\n2. Formát\n3. Príklad\n4. Nuansy",
        "q_prog":      "Analyzuj program Fanuc:\n%@\n1. Čo robí\n2. Rozbor\n3. Chyby\n4. Odporúčania",
        "q_photo":     "Analyzuj foto zo stroja Fanuc. Čo vidíš? Alarmy/chyby? Odporúčania.\nOtázka: %@",
        "q_photo0":    "Analyzuj foto zo stroja Fanuc. Čo vidíš? Alarmy/chyby? Daj odporúčania.",
        "badge_alarm": "Alarm",
        "badge_code":  "Kód",
        "badge_prog":  "Program",
        "badge_photo": "Foto",
        "badge_chat":  "Chat",
        "title_chat":    "Chat s AI",
        "title_alarms":  "Dešifrovanie alarmov",
        "title_codes":   "Vysvetlenie kódov",
        "title_program": "Analýza programu",
        "title_photo":   "Foto analýza",
        "title_history": "História",
        "title_machine": "Profil stroja",
        "machine_saved":         "Uložené",
        "machine_save_btn":      "Uložiť profil",
        "mach_model":            "MODEL STROJA",
        "mach_model_ph":         "Napr.: Fanuc 0i-MF",
        "mach_ctrl":             "RIADIACI SYSTÉM",
        "mach_ctrl_ph":          "Napr.: Fanuc 0i-MD",
        "mach_axes":             "OSI",
        "mach_axes_ph":          "Napr.: X, Y, Z, A",
        "mach_maxspeed":         "MAX. OTÁČKY OT/MIN",
        "mach_maxspeed_ph":      "Napr.: 8000",
        "mach_maxfeed":          "MAX. POSUV MM/MIN",
        "mach_maxfeed_ph":       "Napr.: 10000",
        "mach_tools":            "NÁSTROJE / ZÁSOBNÍK",
        "mach_tools_ph":         "Napr.: 24 nástrojov, BT40",
        "mach_materials":        "SPRACOVÁVANÉ MATERIÁLY",
        "mach_materials_ph":     "Napr.: oceľ, hliník, nerezová oceľ",
        "mach_tolerances":       "TOLERANCIE",
        "mach_tolerances_ph":    "Napr.: ±0.01 mm",
        "mach_postproc":         "POSTPROCESOR / VLASTNOSTI",
        "mach_postproc_ph":      "Napr.: Heidenhain, podprogramy, makrá",
        "mach_notes":            "POZNÁMKY O STROJI",
        "mach_notes_ph":         "Akékoľvek ďalšie informácie...",
        "prog_chat_ph":          "Zadajte doplňujúcu otázku k programu...",
        "btn_improve":           "Vylepšiť kód",
        "btn_improve_explain":   "Čo vylepšiť",
        "improved_code_lbl":     "VYLEPŠENÝ KÓD",
        "improve_explain_lbl":   "ČO BOLO VYLEPŠENÉ",
        "q_prog_machine":        "Analyzuj program Fanuc s ohľadom na parametre stroja:\n\nSTROJ:\n%@\n\nPROGRAM:\n%@\n\n1. Čo robí program\n2. Rozbor príkazov\n3. Chyby a nezrovnalosti\n4. Odporúčania",
        "q_improve":             "Vylepši tento program Fanuc:\n\nSTROJ:\n%@\n\nPROGRAM:\n%@\n\nVráť:\n1. VYSVETLENIE: čo bolo vylepšené\n2. VYLEPŠENÝ KÓD: hotový G-kód",
        "q_improve_explain":     "Vysvetli čo sa dá vylepšiť (bez kódu):\n\nSTROJ:\n%@\n\nPROGRAM:\n%@\n\n1. Čo nie je optimálne\n2. Čo vylepšiť\n3. Problémy\n4. Odporúčania",
        "model_label":           "Model",
        "send":                  "Odoslať",
        "loading":               "Načítavanie...",
        "copy":                  "Kopírovať",
        "delete":                "Odstrániť",
        "rename":                "Premenovať",
        "ok":                    "OK",
        "no_results":            "Bez výsledkov",
        "more":                  "Viac",
    ]

    // MARK: - EN
    private static let en: [String: String] = [
        "nav_chat":    "AI Chat",
        "nav_alarms":  "Alarms",
        "nav_codes":   "G/M Codes",
        "nav_program": "Program Analysis",
        "nav_photo":   "Photo Analysis",
        "nav_history": "History",
        "nav_machine": "Machine Profile",
        "settings":    "Settings",
        "language":    "Language",
        "alarm_label": "ALARM CODE",
        "alarm_ph":    "e.g. 607, SV0401, EX1082",
        "alarm_quick": "COMMON ALARMS",
        "code_label":  "G OR M CODE",
        "code_ph":     "e.g. M30, G01, G54",
        "code_quick":  "POPULAR CODES",
        "prog_label":  "G-CODE PROGRAM",
        "prog_ph":     "Paste G-code...",
        "photo_label": "PHOTO ANALYSIS",
        "photo_hint":  "Attach a photo of the machine screen or part\nAI will identify alarms and give recommendations",
        "photo_add":   "📎  Attach photo",
        "photo_go":    "Analyze",
        "photo_q_ph":  "Question about this photo (optional)...",
        "photo_none":  "No photo selected",
        "photo_err":   "Select a photo",
        "photo_camera":"Camera",
        "photo_gallery":"Gallery",
        "chat_ph":     "Ask a CNC question...",
        "chat_attach": "📎",
        "chat_send":   "Send",
        "chat_new":    "New chat",
        "chat_welcome":"Hello! I'm your Fanuc CNC AI assistant.\n\nI can help with:\n• Decoding alarms\n• Explaining G/M codes\n• Analyzing programs\n• Diagnosing via photo\n\nType a question or attach a photo 👇",
        "btn_analyze": "Decode",
        "btn_explain": "Explain",
        "btn_prog":    "Analyze",
        "result_title":"RESULT",
        "result_empty":"Result will appear here...",
        "hist_title":  "History",
        "hist_clear":  "Clear",
        "hist_empty":  "History is empty",
        "status_ready":"Ready",
        "status_busy": "Analyzing...",
        "set_title":   "Settings",
        "api_lbl":     "ANTHROPIC API KEY",
        "api_hint":    "console.anthropic.com  —  registration gives $5 free",
        "api_save_cb": "Remember key",
        "save":        "Save",
        "cancel":      "Cancel",
        "err_key":     "Configure API key in Settings",
        "err_empty":   "Enter a value",
        "err_prog":    "Paste G-code",
        "sys":         "You are a Fanuc CNC expert. IMPORTANT: always reply ONLY in English, even if previous messages were in another language. Give specific solutions.",
        "q_alarm":     "Decode Fanuc alarm: %@\n1. Meaning\n2. Causes\n3. Fix steps\n4. Prevention",
        "q_code":      "Explain Fanuc G/M code: %@\n1. What it does\n2. Format\n3. Example\n4. Notes",
        "q_prog":      "Analyze Fanuc program:\n%@\n1. What it does\n2. Breakdown\n3. Errors\n4. Recommendations",
        "q_photo":     "Analyze this Fanuc CNC photo. What do you see? Alarms/errors? Recommendations.\nQuestion: %@",
        "q_photo0":    "Analyze this Fanuc CNC photo. What do you see? Alarms/errors? Give recommendations.",
        "badge_alarm": "Alarm",
        "badge_code":  "Code",
        "badge_prog":  "Program",
        "badge_photo": "Photo",
        "badge_chat":  "Chat",
        "title_chat":    "AI Chat",
        "title_alarms":  "Alarm Decoder",
        "title_codes":   "Code Reference",
        "title_program": "Program Analysis",
        "title_photo":   "Photo Analysis",
        "title_history": "History",
        "title_machine": "Machine Profile",
        "machine_saved":         "Saved",
        "machine_save_btn":      "Save profile",
        "mach_model":            "MACHINE MODEL",
        "mach_model_ph":         "e.g. Fanuc 0i-MF",
        "mach_ctrl":             "CONTROLLER",
        "mach_ctrl_ph":          "e.g. Fanuc 0i-MD",
        "mach_axes":             "AXES",
        "mach_axes_ph":          "e.g. X, Y, Z, A",
        "mach_maxspeed":         "MAX SPEED RPM",
        "mach_maxspeed_ph":      "e.g. 8000",
        "mach_maxfeed":          "MAX FEED MM/MIN",
        "mach_maxfeed_ph":       "e.g. 10000",
        "mach_tools":            "TOOLS / MAGAZINE",
        "mach_tools_ph":         "e.g. 24 tools, BT40",
        "mach_materials":        "MATERIALS",
        "mach_materials_ph":     "e.g. steel, aluminum, stainless",
        "mach_tolerances":       "TOLERANCES",
        "mach_tolerances_ph":    "e.g. ±0.01 mm",
        "mach_postproc":         "POSTPROCESSOR / FEATURES",
        "mach_postproc_ph":      "e.g. Heidenhain, subprograms, macros",
        "mach_notes":            "MACHINE NOTES",
        "mach_notes_ph":         "Any additional information...",
        "prog_chat_ph":          "Ask a follow-up question about the program...",
        "btn_improve":           "Improve code",
        "btn_improve_explain":   "What to improve",
        "improved_code_lbl":     "IMPROVED CODE",
        "improve_explain_lbl":   "WHAT WAS IMPROVED",
        "q_prog_machine":        "Analyze this Fanuc program considering machine parameters:\n\nMACHINE:\n%@\n\nPROGRAM:\n%@\n\n1. What program does\n2. Command breakdown\n3. Errors/discrepancies\n4. Recommendations",
        "q_improve":             "Improve this Fanuc program:\n\nMACHINE:\n%@\n\nPROGRAM:\n%@\n\nReturn:\n1. EXPLANATION: what was improved\n2. IMPROVED CODE: finished G-code",
        "q_improve_explain":     "Explain what could be improved (no code):\n\nMACHINE:\n%@\n\nPROGRAM:\n%@\n\n1. What's not optimal\n2. What to improve\n3. Problems\n4. Recommendations",
        "model_label":           "Model",
        "send":                  "Send",
        "loading":               "Loading...",
        "copy":                  "Copy",
        "delete":                "Delete",
        "rename":                "Rename",
        "ok":                    "OK",
        "no_results":            "No results",
        "more":                  "More",
    ]

    // MARK: - UA (Українська)
    private static let ua: [String: String] = [
        "nav_chat":    "Чат з AI",
        "nav_alarms":  "Алярми",
        "nav_codes":   "G/M Коди",
        "nav_program": "Аналіз програми",
        "nav_photo":   "Фото аналіз",
        "nav_history": "Історія",
        "nav_machine": "Профіль верстата",
        "settings":    "Налаштування",
        "language":    "Мова",
        "alarm_label": "НОМЕР АЛЯРМУ",
        "alarm_ph":    "Наприклад: 607, SV0401, EX1082",
        "alarm_quick": "ЧАСТІ АЛЯРМИ",
        "code_label":  "G АБО M КОД",
        "code_ph":     "Наприклад: M30, G01, G54",
        "code_quick":  "ПОПУЛЯРНІ КОДИ",
        "prog_label":  "G-КОД ПРОГРАМИ",
        "prog_ph":     "Вставте G-код...",
        "photo_label": "ФОТО АНАЛІЗ",
        "photo_hint":  "Прикріпіть фото екрана верстата або деталі\nAI визначить алярми і дасть рекомендації",
        "photo_add":   "📎  Прикріпити фото",
        "photo_go":    "Аналізувати",
        "photo_q_ph":  "Питання по фото (необов’язково)...",
        "photo_none":  "Фото не вибрано",
        "photo_err":   "Виберіть фото",
        "photo_camera":"Камера",
        "photo_gallery":"Галерея",
        "chat_ph":     "Напишіть питання по ЧПК...",
        "chat_attach": "📎",
        "chat_send":   "Надіслати",
        "chat_new":    "Новий чат",
        "chat_welcome":"Привіт! Я AI-асистент по Fanuc CNC.\n\nМожу допомогти з:\n• Розшифровкою алярмів\n• Поясненням G/M кодів\n• Аналізом програм\n• Діагностикою по фото\n\nПишіть питання або прикріпіть фото 👇",
        "btn_analyze": "Розшифрувати",
        "btn_explain": "Пояснити",
        "btn_prog":    "Проаналізувати",
        "result_title":"РЕЗУЛЬТАТ",
        "result_empty":"Результат з’явиться тут...",
        "hist_title":  "Історія",
        "hist_clear":  "Очистити",
        "hist_empty":  "Історія порожня",
        "status_ready":"Готовий до роботи",
        "status_busy": "Аналізую...",
        "set_title":   "Налаштування",
        "api_lbl":     "ANTHROPIC API KEY",
        "api_hint":    "console.anthropic.com  —  реєстрація дає $5 безкоштовно",
        "api_save_cb": "Запам’ятати ключ",
        "save":        "Зберегти",
        "cancel":      "Скасувати",
        "err_key":     "Введіть API ключ у Налаштуваннях",
        "err_empty":   "Введіть значення",
        "err_prog":    "Вставте G-код",
        "sys":         "Ти експерт з ЧПК верстатів Fanuc. ВАЖЛИВО: завжди відповідай ВИКЛЮЧНО українською мовою, навіть якщо попередні повідомлення були іншою мовою. Давай конкретні рішення.",
        "q_alarm":     "Розшифруй алярм Fanuc: %@\n1. Що означає\n2. Причини\n3. Як виправити\n4. Як запобігти",
        "q_code":      "Поясни G/M код Fanuc: %@\n1. Що робить\n2. Формат\n3. Приклад\n4. Нюанси",
        "q_prog":      "Проаналізуй програму Fanuc:\n%@\n1. Що робить\n2. Розбір команд\n3. Помилки\n4. Рекомендації",
        "q_photo":     "Проаналізуй фото з верстата Fanuc. Що бачиш? Є алярми/помилки? Рекомендації.\nПитання: %@",
        "q_photo0":    "Проаналізуй фото з верстата Fanuc. Що бачиш? Є алярми/помилки? Дай рекомендації.",
        "badge_alarm": "Алярм",
        "badge_code":  "Код",
        "badge_prog":  "Програма",
        "badge_photo": "Фото",
        "badge_chat":  "Чат",
        "title_chat":    "Чат з AI",
        "title_alarms":  "Розшифровка алярмів",
        "title_codes":   "Пояснення кодів",
        "title_program": "Аналіз програми",
        "title_photo":   "Фото аналіз",
        "title_history": "Історія",
        "title_machine": "Профіль верстата",
        "machine_saved":         "Збережено",
        "machine_save_btn":      "Зберегти профіль",
        "mach_model":            "МОДЕЛЬ ВЕРСТАТА",
        "mach_model_ph":         "Наприклад: Fanuc 0i-MF",
        "mach_ctrl":             "СТІЙКА (КОНТРОЛЕР)",
        "mach_ctrl_ph":          "Наприклад: Fanuc 0i-MD",
        "mach_axes":             "ОСІ",
        "mach_axes_ph":          "Наприклад: X, Y, Z, A",
        "mach_maxspeed":         "МАКС. ШВИДКІСТЬ ОБ/ХВ",
        "mach_maxspeed_ph":      "Наприклад: 8000",
        "mach_maxfeed":          "МАКС. ПОДАЧА ММ/ХВ",
        "mach_maxfeed_ph":       "Наприклад: 10000",
        "mach_tools":            "ІНСТРУМЕНТИ / МАГАЗИН",
        "mach_tools_ph":         "Наприклад: 24 інструменти, BT40",
        "mach_materials":        "ОБРОБЛЮВАНІ МАТЕРІАЛИ",
        "mach_materials_ph":     "Наприклад: сталь, алюміній, нержавійка",
        "mach_tolerances":       "ДОПУСКИ",
        "mach_tolerances_ph":    "Наприклад: ±0.01 мм",
        "mach_postproc":         "ПОСТПРОЦЕСОР / ОСОБЛИВОСТІ",
        "mach_postproc_ph":      "Наприклад: Heidenhain, підпрограми, макроси",
        "mach_notes":            "ЗАМІТКИ ПРО ВЕРСТАТ",
        "mach_notes_ph":         "Будь-яка додаткова інформація...",
        "prog_chat_ph":          "Поставте уточнююче питання по програмі...",
        "btn_improve":           "Покращити код",
        "btn_improve_explain":   "Що покращити",
        "improved_code_lbl":     "ПОКРАЩЕНИЙ КОД",
        "improve_explain_lbl":   "ЩО ПОКРАЩЕНО",
        "q_prog_machine":        "Проаналізуй програму Fanuc з урахуванням параметрів верстата:\n\nВЕРСТАТ:\n%@\n\nПРОГРАМА:\n%@\n\n1. Що робить програма\n2. Розбір команд\n3. Помилки і невідповідності\n4. Рекомендації",
        "q_improve":             "Покращи цю програму Fanuc:\n\nВЕРСТАТ:\n%@\n\nПРОГРАМА:\n%@\n\nПоверни:\n1. ПОЯСНЕННЯ: що було покращено\n2. ПОКРАЩЕНИЙ КОД: готовий G-код",
        "q_improve_explain":     "Поясни, що можна покращити (без коду):\n\nВЕРСТАТ:\n%@\n\nПРОГРАМА:\n%@\n\n1. Що не оптимально\n2. Що покращити\n3. Проблеми\n4. Рекомендації",
        "model_label":           "Модель",
        "send":                  "Надіслати",
        "loading":               "Завантаження...",
        "copy":                  "Копіювати",
        "delete":                "Видалити",
        "rename":                "Перейменувати",
        "ok":                    "OK",
        "no_results":            "Немає результатів",
        "more":                  "Ще",
    ]

    // MARK: - Доступ
    static func string(_ key: String, lang: AppLanguage) -> String {
        let dict: [String: String]
        switch lang {
        case .ru: dict = ru
        case .sk: dict = sk
        case .en: dict = en
        case .ua: dict = ua
        }
        return dict[key] ?? key
    }
}
